version: "3"
services:
# ===========================================================
  # Auth Service and Database
# ===========================================================
  auth-service:
    build: ./auth-service
    ports:
      - "9010:9010"
    environment:
      DB_URL: auth-db
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - auth-db
      - rabbitmq
    restart: on-failure

  auth-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: testsecret
      POSTGRES_USER: test
      POSTGRES_DB: test
    volumes:
      - auth-data:/var/lib/postgresql/data 
  
# ===========================================================
  # Product Service and Database
# ===========================================================
  
  product-service:
    build: ./product-service
    ports:
      - "9011:9011"
    environment:
      DB_URL: product-db
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - product-db
      - auth-service
      - rabbitmq
    restart: on-failure



  product-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: testsecret
      POSTGRES_USER: test
      POSTGRES_DB: test
    volumes:
      - product-data:/var/lib/postgresql/data

 #===========================================================
  # Cart Service and Database
 #===========================================================
      
  cart-service:
    build: ./cart-service
    ports:
      - "9012:9012"
    environment:
      DB_URL: cart-db
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - cart-db
      - auth-service
      - rabbitmq
    restart: on-failure

  cart-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: testsecret
      POSTGRES_USER: test
      POSTGRES_DB: test
    volumes:
      - cart-data:/var/lib/postgresql/data
      
 #===========================================================
   #Message broker using Rabbit MQ 
 #===========================================================

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "8081:15672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq


volumes:
  auth-data:
  product-data:
  cart-data:
  rabbitmq-data:



