version: "3"
services:
      
# ===========================================================
  # Nginx
# ===========================================================
  nginx:
    image: nginx
    container_name: nginx  
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static:/usr/share/nginx/html/static
      - share-data:/usr/share/nginx/html/static/images
    depends_on:
      - product-service
    restart: on-failure

# ===========================================================
  # Auth Service and Database
# ===========================================================
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "9010:9010"
    environment:
      DB_URL: auth-db
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - auth-db
      - rabbitmq
    restart: on-failure

  auth-db:
    image: postgres
    container_name: auth-db
    environment:
      POSTGRES_PASSWORD: testsecret
      POSTGRES_USER: test
      POSTGRES_DB: test
    volumes:
      - auth-data:/var/lib/postgresql/data 
  
# ===========================================================
  # Product Service and Database
# ===========================================================
  
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "9011:9011"
    environment:
      DB_URL: product-db
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - share-data:/app/images
    depends_on:
      - product-db
      - auth-service
      - rabbitmq
    restart: on-failure

  product-db:
    image: postgres
    container_name: product-db
    environment:
      POSTGRES_PASSWORD: testsecret
      POSTGRES_USER: test
      POSTGRES_DB: test
    volumes:
      - product-data:/var/lib/postgresql/data

 #===========================================================
  # Cart Service and Database
 #===========================================================
      
  cart-service:
    build: ./cart-service
    container_name: cart-service
    ports:
      - "9012:9012"
    environment:
      DB_URL: cart-db
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - cart-db
      - auth-service
      - rabbitmq
    restart: on-failure

  cart-db:
    image: postgres
    container_name: cart-db
    environment:
      POSTGRES_PASSWORD: testsecret
      POSTGRES_USER: test
      POSTGRES_DB: test
    volumes:
      - cart-data:/var/lib/postgresql/data
      
 #===========================================================
  # Order Service and Database
 #===========================================================
      
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "9013:9013"
    environment:
      DB_URL: order-db
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - order-db
      - auth-service
      - rabbitmq
    restart: on-failure

  order-db:
    image: postgres
    container_name: order-db
    environment:
      POSTGRES_PASSWORD: testsecret
      POSTGRES_USER: test
      POSTGRES_DB: test
    volumes:
      - order-data:/var/lib/postgresql/data

 #===========================================================
  # Payment Service and Database
 #===========================================================
      
  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "9014:9014"
    environment:
      DB_URL: payment-db
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - payment-db
      - auth-service
      - rabbitmq
    restart: on-failure

  payment-db:
    image: postgres
    container_name: payment-db
    environment:
      POSTGRES_PASSWORD: testsecret
      POSTGRES_USER: test
      POSTGRES_DB: test
    volumes:
      - payment-data:/var/lib/postgresql/data
 #===========================================================
   #Message broker using Rabbit MQ 
 #===========================================================

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "8082:15672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq


volumes:
  auth-data:
  product-data:
  cart-data:
  order-data:
  payment-data:
  rabbitmq-data:
  share-data:



